version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: builder # Use builder stage for development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  admin:
    build:
      context: ./admin
      target: builder # Use builder stage for development
    ports:
      - "3001:3001"
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  # バックエンドサービスは後で追加予定
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped 